[build]
target = "avr-none"
rustflags = ["-C", "target-cpu=atmega2560", "-C", "opt-level=3", "-C", "lto=true", "-C", "codegen-units=1"]

[target.'cfg(target_arch = "avr")']
runner = "ravedude"

[unstable]
build-std = ["core"]
